version: "3.5"
services:
  predictor:
    build: .
    volumes:
      - type: bind
        source: ./signals
        target: /home/node/signals
      - type: bind
        source: ./logs
        target: /home/node/logs
      - type: bind
        source: ./uploads
        target: /home/node/uploads
    env_file:
      - .env
    restart: always
    networks:
      - master
networks:
  master:
    name: master

  